@startuml

class Mundo{
    - habitacion: Habitacion
    - gato: Gato 
    + Mundo()
    + empezar()
    + main()
}

class Habitacion {
    - baldosas[][]: Baldosa
    + largo: int
    + ancho: int
    +Habitacion(largo: int, ancho: int)
    +imprimir()
    +ensuciar(posicionX: int,posicionY: int)
    -imprimeLinea()
    -borraPantalla()
}

class Baldosa{
    - baldosa: int
    + Baldosa()
    - inicializaEstado(): int
    + int ver()
    + ensucia()
}

class Gato{

    + Gato(habitacion: Habitacion)
    + ensuciar(habitacion: Habitacion)
}

class Aspiradora{

    + Aspiradora(habitacion: Habitacion)
    + limpiar(habitacion: Habitacion)
}

abstract Elemento{
    + posicionX: int
    + posicionY: int
    + mover(habitacion: Habitacion)
}

Elemento <|--- Gato 
Elemento <|--- Aspiradora 

Mundo *-D--> Habitacion
Mundo *-R---> Gato
Mundo *-L---> Aspiradora
Habitacion *-D--> Baldosa 
Habitacion ... Gato
Habitacion ... Aspiradora

@enduml