@startuml

class Main {
    + main()
}

class Mundo{
    - habitacion: Habitacion
    - gato: Gato 
    + Mundo()
    + imprimir(Gato[] gatos)
    - hayUnGato(Gato[] gatos, int i, int j)
    + empezar()
}

class Habitacion {
    + baldosas[][]: Baldosa
    + largo: int
    + ancho: int
    + Habitacion(largo: int, ancho: int)
    + imprimir()
    + ensuciar(posicionX: int,posicionY: int)
    - imprimeLinea()
    - borraPantalla()
}

class Baldosa{
    - estado: int
    + Baldosa()
    - int inicializaEstado()
    + int ver()
    + ensucia()
}

class Gato{
    + Gato(Habitacion: habitacion)
    + mover(Habitacion: habitacion)
    + ensuciar(Habitacion: habitacion)
}

class Movimiento {
    + posicionX: int
    + posicionY: int
    + Movimiento(Habitacion: habitacion)
    + mover(Habitacion: habitacion)
}

Main *--- Mundo
Mundo *--- Habitacion
Mundo *--- Gato
Habitacion *--- Baldosa 
Habitacion ... Gato
Movimiento ... Gato
@enduml