@startuml

class Mundo {
    - habitacion: Habitacion
    - gatos: Gato[]
    + Mundo()
    + empezar()
    + main()
}

class Habitacion {
    - baldosas: Baldosa[][]
    + largo: int
    + ancho: int
    + Habitacion(largo: int, ancho: int)
    + imprimir()
    + ensuciar(posicionX: int, posicionY: int)
}

class Baldosa {
    - estado: int
    + Baldosa()
    + ver(): int
    + ensuciar()
}

class Gato {
    + posicionX: int
    + posicionY: int
    + Gato(posicionX: int, posicionY: int)
    + mover(direccion: Direccion)
    + ensuciar(habitacion: Habitacion)
}

enum Direccion {
    ARRIBA
    ABAJO
    IZQUIERDA
    DERECHA
}

Mundo *-down-> Habitacion
Mundo *--right-> Gato
Habitacion *-down-> Baldosa
Gato *-- Direccion

@enduml
