@startuml

class Mundo{
    + Habitacion[]: habitaciones
    + Mundo()
    - iniciarMundo()
    - continuar
    + main()
}

class Habitacion {
    - Baldosa[][]: baldosas
    - Gato[]: Gato
    + int ancho
    + int largo
    + Habitacion(int ancho, int largo, int cantidadDeGatos)
    + pasarTiempo()
    - imprimirHabitacion()
    - hayGato()
    - parsear()
    - printBorder()
    - limpiarPantalla()
    + ensuciarBaldosa(int posicionX, int posicionY)
    + cambiarPosicionGato()
    - posicionInicialGato()
}

class Baldosa{
    + int estado
    + Baldosa()
    - definirEstadoInicial()
    + ensuciar()
    + suciedad()
}

class Gato{
    + int posicionX
    + int posicionY
    + Gato(Habitacion habitacion)
    + moverse(Habitacion habitacion)
    + ensuciar(Habitacion habitacion)

}

Mundo *-D-- Habitacion

Habitacion *-D-- Baldosa 
Habitacion ... Gato

@enduml